In [46]:
import numpy as np
import pandas as pd

In [72]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.metrics import  confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt


In [48]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/Diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [49]:
X = df.drop(columns = ['Outcome'], axis = 1)
Y = df['Outcome']
print(X.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')


In [50]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


In [51]:
# split into training and test set(70% training, 30% testing)
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled,Y, test_size = 0.3, random_state = 42)


**Implement Classification Model**

In [52]:
#initialize decisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)



DecisionTreeClassifier()

In [65]:
prediction = model.predict(X_test)  #y_pred ho yo predictions bhnya
prediction

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [54]:
#initialize RandomForestClassifier
model1 = RandomForestClassifier(n_estimators = 100, random_state=42)
model1.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [55]:
prediction1 = model1.predict(X_test)
prediction1

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [56]:
#checking accuracy for decision tree classifier
accuracy = accuracy_score(Y_test, prediction)
accuracy

0.6883116883116883

In [57]:
#conf matrix for decision tree classifier
conf_matrix = confusion_matrix(Y_test, prediction)
conf_matrix

array([[105,  46],
       [ 26,  54]])

In [59]:
#checking accuracy for RandomForestClassifier
accuracy1 = accuracy_score(Y_test, prediction1)
accuracy1

0.7575757575757576

In [60]:
#conf_matrix for randomforestclassifier
conf_matrix1 = confusion_matrix(Y_test, prediction1)
conf_matrix1

array([[122,  29],
       [ 27,  53]])

In [62]:
#display F1 Scores
dt_f1 = f1_score(Y_test, prediction, average = 'weighted')
rf_f1 = f1_score(Y_test, prediction1, average = 'weighted')
print(f"Decision tree F1 Score: {dt_f1:.2f}")
print(f"Random forest F1 Score: {rf_f1:.2f}")

Decision tree F1 Score: 0.69
Random forest F1 Score: 0.76


**Cross Validation**(use grid or random CV)
Hyperparameter Tuning:

In [66]:
# parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100,200,300],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5, 10],
}


In [69]:
#Print best parameter and best Cross-validation score
grid_search = GridSearchCV(model1, param_grid, cv = 5, scoring = 'neg_mean_squared_error')
grid_search.fit(X_train, Y_train)

#print the best parameters and best cross-validation score
print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation score: ", grid_search.best_score_)


Best parameters:  {'max_depth': 20, 'min_samples_split': 2, 'n_estimators': 300}
Best cross-validation score:  -0.21976462443752162


**Implement Regression Model**

In [73]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

**Decision Tree Regressor**

In [74]:
#initialize model forest Regressor
model = DecisionTreeRegressor()
model.fit(X_train, Y_train)

DecisionTreeRegressor()

In [75]:
y_pred = model.predict(X_test)
y_pred

array([0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 1.

In [84]:
#checking accuracy
mse = mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

print("Decision Tree Regression Mean Squared Error: ", mse)
print("Decision Tree Regression R squared: ", r2)

Decision Tree Regression Mean Squared Error:  0.17546709956709955
Decision Tree Regression R squared:  0.2249089486754965


**Random Forest Regression**

In [88]:
model1 = RandomForestRegressor()
model1.fit(X_train, Y_train)


RandomForestRegressor()

In [92]:
y_pred1 = model1.predict(X_test)
y_pred1

array([0.53, 0.34, 0.08, 0.08, 0.44, 0.65, 0.  , 0.7 , 0.59, 0.74, 0.29,
       0.91, 0.28, 0.54, 0.01, 0.33, 0.03, 0.  , 0.62, 0.66, 0.47, 0.06,
       0.26, 0.  , 0.63, 0.99, 0.02, 0.02, 0.14, 0.1 , 0.87, 0.89, 0.82,
       0.81, 0.51, 0.65, 0.93, 0.46, 0.19, 0.78, 0.05, 0.56, 0.77, 0.5 ,
       0.03, 0.81, 0.52, 0.07, 0.06, 0.95, 0.  , 0.81, 0.7 , 0.2 , 0.14,
       0.01, 0.7 , 0.  , 0.19, 0.82, 0.65, 0.11, 0.2 , 0.45, 0.02, 0.65,
       0.  , 0.52, 0.03, 0.86, 0.61, 0.15, 0.06, 0.01, 0.06, 0.4 , 0.14,
       0.04, 0.03, 0.13, 0.82, 0.14, 0.18, 0.54, 0.17, 0.98, 0.65, 0.47,
       0.33, 0.01, 0.1 , 0.11, 0.01, 0.69, 0.39, 0.64, 0.69, 0.04, 0.79,
       0.04, 0.83, 0.01, 0.54, 0.67, 0.88, 0.25, 0.22, 0.98, 0.07, 0.78,
       0.  , 0.63, 0.16, 0.9 , 0.33, 0.38, 0.82, 0.44, 0.08, 0.6 , 0.  ,
       0.23, 0.42, 0.03, 0.3 , 0.47, 0.31, 0.67, 0.74, 0.6 , 0.76, 0.65,
       0.05, 0.41, 0.93, 0.56, 0.23, 0.72, 0.8 , 0.  , 0.08, 0.  , 0.19,
       0.54, 0.06, 0.25, 0.28, 0.  , 0.25, 0.76, 0.

In [93]:
#Mean squared error and r-squared
mse = mean_squared_error(Y_test, y_pred1)
r2 = r2_score(Y_test, y_pred1)

print("Random Forest Regression Mean Squared Error: ", mse)
print("Random Forest Regression R squared: ", r2)

Random Forest Regression Mean Squared Error:  0.1733116883116883
Random Forest Regression R squared:  0.23443004966887404


**HyperParameter Tuning using RandomSearchCV**

In [94]:
rf_grid = {
    'n_estimators': [100, 200, 100],
    'max_depth': [10,20, None],
    'min_samples_split': [2,5,10],
    'min_samples_leaf': [1,2,4]
}

In [96]:
random_search = RandomizedSearchCV(model1, param_distributions = rf_grid, cv = 5, scoring ='neg_mean_squared_error')
random_search.fit(X_train, Y_train)
#print the best parameters and best cross-validation score
print("Best parameters: ", random_search.best_params_)
print("Best cross-validation score: ", random_search.best_score_)




Best parameters:  {'n_estimators': 200, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_depth': 20}
Best cross-validation score:  -0.15381382330107338
